### ISSUE TITLE
Colour Theme

### ISSUE THREAD

**Issue by Grim4Reaper** [EddieTheEd/obsidiannotes-v.3#5]
**Describe the bug**
The colour theme of your website makes it hard to read some of the darker text. PLEASE FIX.

**Comment by EddieTheEd** [comment]
1. acquire glasses
2. you are probably using lightmode, stop
3. if you aren't using lightmode then i have no clue what you are complaining about. you are fabricating random things that you think are issues
4. this is actually an intentional feature to disenfranchise the blind. i dont want them getting stuff from my website
4a. that was a joke
